config-version = 2
start-at-login = true
persistent-workspaces = []
accordion-padding = 0
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focus-changed = ['move-mouse window-lazy-center']
[gaps]
inner.horizontal = 0
inner.vertical = 0
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0
[key-mapping]
preset = 'qwerty'
[mode.main.binding]
cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"
# apps
cmd-enter = "exec-and-forget open -a /Applications/Ghostty.app"
alt-s = 'exec-and-forget open -a /Applications/Safari.app/'
alt-t = 'exec-and-forget open -a /Applications/Telegram.app/'
# keys binding
alt-c = [
    'exec-and-forget open -a /Applications/kitty.app',
    'exec-and-forget open -a /Applications/Safari.app'
]
# focus (vim-style)
alt-left ='focus --boundaries-action wrap-around-the-workspace left'
alt-down ='focus --boundaries-action wrap-around-the-workspace down'
alt-up ='focus --boundaries-action wrap-around-the-workspace up'
alt-right = 'focus --boundaries-action wrap-around-the-workspace right'
# move windows
alt-shift-left = 'move left'
alt-shift-down = 'move down'
alt-shift-up = 'move up'
alt-shift-right = 'move right'
# workspaces
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
# move to workspace
alt-shift-1 = 'move-node-to-workspace 1 --focus-follows-window'
alt-shift-2 = 'move-node-to-workspace 2 --focus-follows-window'
alt-shift-3 = 'move-node-to-workspace 3 --focus-follows-window'
alt-shift-4 = 'move-node-to-workspace 4 --focus-follows-window'
# back & forth (как i3)
alt-tab = 'workspace-back-and-forth'
# service mode (как i3 "mode")
alt-shift-semicolon = 'mode service'
alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'
alt-f = 'fullscreen'
# 🔧 SERVICE MODE
[mode.service.binding]
esc = ['reload-config', 'mode main']
# reset layout
r = ['flatten-workspace-tree', 'mode main']
# toggle floating
f = ['layout floating tiling', 'mode main']
# close others
backspace = ['close-all-windows-but-current', 'mode main']
#logic for place app in specfic screen
# terminal → 1
[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
run = "move-node-to-workspace 1"
# browser → 2
[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = "move-node-to-workspace 2 --focus-follows-window"
[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = "move-node-to-workspace 4 --focus-follows-window"
# other apps
[[on-window-detected]]
if="true"
run = "move-node-to-workspace 3 --focus-follows-window"
