# ==============================
# ULTRA-FAST KITTY CONFIG
# ==============================

# Font
font_family      JetBrains Mono
italic_font      auto
bold_font        auto
bold_italic_font auto
font_size        20
font_size_delta  0

# Window
window_decorations no
background_opacity 1
window_padding_width 0

# Cursor
cursor_shape block
cursor_shape_unfocused beam

# Scrolling
map opt+cmd+up scroll_line_up
map opt+cmd+down scroll_line_down
map shift+cmd+up scroll_page_up
map shift+cmd+down scroll_page_down

# Background
background_image      /Users/max/Pictures/black_and_red.jpg
background_image_layout cscaled
background_tint       0.9
background_tint_gaps  -10

# Bells
enable_audio_bell yes

# Ultra-fast exit
confirm_exit no
confirm_os_window_close 0
